# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  TiHom
subtitle: 虚拟的人生自己编写
name: TiHom 
email: 13652493839@163.com
description: 本站是TiHom的技术分享博客。内容涵盖生活故事、Java后端技术、Spring Boot、Spring Cloud、SSM、JVM、中间件使用、系统监控等相关的研究与知识分享。
keywords: 
encoding: "utf-8"
favicon: favicon.png 

repository: tihomcode/tihomcode.github.io
github_url: https://github.com/tihomcode
cnblog_url: https://blog.csdn.net/tryandfight
url: http://www.tihom.top
enforce_ssl: 

## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata
  - jekyll-octicons
  
# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: rouge

syntax_highlighter_opts:
   coderay_line_numbers:  nil

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:

  -
    href: /
    label: Home

  -
    href: /project.html
    label: Project

  -
    href: /blog.html
    label: All

  -
    href: /archives.html
    label: Archives

  -
    href: /link.html
    label: Link

  -
    href: /about.html
    label: About


# labels. my blog key words
labels:

  # -
  #   href: /share/2017/10/01/resource-sharing.html
  #   name: 资源

  -
    href: /life.html
    name: 故事

  -
    href: /j2se.html
    name: Java基础
    
  -
    href: /jvm.html
    name: JVM

  -
    href: /source.html
    name: 源码

  -
    href: /mysql.html
    name: MySQL

  # -
  #   href: /docker.html
  #   name: Docker

  -
    href: /open-source.html
    name: Code   

# selected articles
classes:

  -
    href: /life.html
    name: 我的故事
    describe: 生活就是故事，故事就是生活

  -
    href: /j2se.html
    name: Java基础
    describe: 勿在浮沙筑高楼

  -
    href: /project.html
    name: 项目系列文章
    describe: 从项目学知识，巩固知识


# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# Sidebar to show popular repo
side_bar_repo_limit: 6 # Number of repos to show

# Google Analytics
# analytics :
# provider : google
#   google :
#     tracking_id : ''  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, MySQL, Oracle, Design Patterns]
skill_j2ee_keywords: [Spring, SpringBoot, Spring Data JPA, MyBatis, Thymeleaf]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, NodeJS, ExpressJS, MongoDB, Redis, PHP,  Boostrap]
skill_mobile_app_keywords: [vuejs, hyhird app]


# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitment
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: tihomcode
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: tihomcode
    repo: blog-comments
    oauth: 
        client_id: 215027f72c00eb7a9e47
        client_secret: b91c0b7f5077edf76666ca73128181339fdb1feb
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: tihomcode
    repo: blog-comments
    clientID: 
    clientSecret: 
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false